[build]
  # Директория с исходным кодом frontend
  base = "frontend"
  
  # Команда для сборки с отключенным ESLint
  command = "CI=false npm run build"
  
  # Директория с собранными файлами
  publish = "build"

[build.environment]
  DISABLE_ESLINT_PLUGIN = "true"
  GENERATE_SOURCEMAP = "false"

# Настройки для Single Page Application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Настройки для API (если нужно проксировать запросы)
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.com/api/:splat"
  status = 200
  force = true

# Настройки для безопасности
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://telegram.org; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://api.telegram.org https://translate-pa.googleapis.com"

# Настройки для статических файлов
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
